### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by jeremy-moore** [maccam912/ppp#3]
Followed instructions on https://docs.plutus-community.com/docs/setup/DockerCompose.html

Last part of output:

#14 304.1  - regex-posix-0.96.0.0 (lib) (requires download & build)
#14 304.1  - random-1.2.0 (lib) (requires download & build)
#14 304.1  - distributive-0.6.2.1 (lib) (requires download & build)
#14 304.1  - ansi-wl-pprint-0.6.9 (lib) (requires download & build)
#14 304.1  - attoparsec-0.14.1 (lib) (requires download & build)
#14 304.1  - uuid-types-1.0.4 (lib) (requires download & build)
#14 304.1  - comonad-5.0.8 (lib) (requires download & build)
#14 304.1  - test-framework-0.8.2.0 (lib) (requires download & build)
#14 304.1  - optparse-applicative-0.15.1.0 (lib) (requires download & build)
#14 304.1  - bifunctors-5.5.10 (lib) (requires download & build)
#14 304.1  - test-framework-hunit-0.3.0.2 (requires download & build)
#14 304.1  - assoc-1.0.2 (lib) (requires download & build)
#14 304.1  - these-1.1.1.1 (lib) (requires download & build)
#14 304.1  - strict-0.4.0.1 (lib) (requires download & build)
#14 304.1  - aeson-1.5.6.0 (lib) (requires download & build)
#14 304.1  - HsYAML-aeson-0.2.0.0 (lib) (requires download & build)
#14 304.1  - stylish-haskell-0.12.2.0 (test:stylish-haskell-tests) (first run)
#14 304.1  - stylish-haskell-0.12.2.0 (lib) (first run)
#14 304.1  - stylish-haskell-0.12.2.0 (exe:stylish-haskell) (first run)
#14 304.5 building '/nix/store/r46fn1pwr9ykf6d23k8ihnfplrdnmnfw-stylish-haskell-plan-to-nix-pkgs.drv'...
#14 305.0 trace: To materialize project.plan-nix for source entirely, pass a writable path as the `materialized` argument and run the 'updateMaterialized' script in 'passthru'.
#14 306.7 copying path '/nix/store/gj3p8i2j6rk41rvw877z2d4jlgphhbaj-source' from 'https://hydra.iohk.io'...
#14 311.0 building '/nix/store/q5gwjj419h5qwxxpkpp7gp7rjip6k2ay-cabal.project.drv'...
#14 311.2 building '/nix/store/dkdiffpjhpcrnwf04f85dvymx7xqpfds-source-plan-to-nix-pkgs.drv'...
#14 311.4 Using index-state 2021-04-13T00:00:00Z
#14 311.5 Warning: The package list for 'hackage.haskell.org-at-2021-04-13T000000Z' is
#14 311.5 18742 days old.
#14 311.5 Run 'cabal update' to get the latest list of available packages.
#14 314.7 Warning: Requested index-state2021-04-13T00:00:00Z is newer than
#14 314.7 'hackage.haskell.org-at-2021-04-13T000000Z'! Falling back to older state
#14 314.7 (2021-04-12T22:47:21Z).
#14 314.9 Resolving dependencies...
------
executor failed running [/bin/sh -c nix-shell --run "exit"]: exit code: 137
ERROR: Service 'server' failed to build

**Comment by maccam912** [comment]
Try giving it more memory to work with. It seems like it might be running out.
